### ISSUE TITLE
关于MMA

### ISSUE THREAD

**Issue by liuqi123123** [wznpub/MMA_Regularization#1]
你好，我把MMA损失函数加到网络中，结果loss值一直是负数，请问这正常吗

**Comment by wzn-cv** [comment]
> 你好，我把MMA损失函数加到网络中，结果loss值一直是负数，请问这正常吗

抱歉，回复晚了。

这是正常的。因为MMA loss使用的是最小夹角的负值，这样随着模型的训练，才能使最小夹角变大。我们关心的是优化所要达到的目的。

如果你想看原始的loss的变化，可以只plot原始的loss，不要plot二者的加和。

**Comment by liuqi123123** [comment]
哦哦，谢谢了，我觉得你的方法在很多领域可以通用。真棒！

**Comment by wzn-cv** [comment]
> 哦哦，谢谢了，我觉得你的方法在很多领域可以通用。真棒！

谢谢你。

如果方便，希望能够给我一些使用的反馈啊。哈哈~

**Comment by liuqi123123** [comment]
那是必须的！
